### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by KeanoSchuman** [ByteZ1337/ParticleLib#10]
Hello, is there a installation guide? Its very helpful is there is.

Please reply :)

**Comment by ByteZ1337** [comment]
Hello,
this is a library, so no installation is needed. Just add the dependency to your pom.xml or download the library and link the jar in your IDE. When compiling your plugin you have 2 options:
- Extract the library into your plugin, so you won't need an extra plugin
- ~~Depend on the library in your plugin.yml.~~

~~If you decide to do the second option every server that runs your plugin also needs the ParticleLib plugin.~~
~~If you still have any questions feel free to ask.~~
