### ISSUE TITLE
Stop Task uses Index instead of Integer object

### ISSUE THREAD

**Issue by CubBossa** [ByteZ1337/ParticleLib#14]
Hey there. I just called the stopTask(taskId) Method in the Taskmanager. It removes the taskId from the running tasks arraylist but as its an int it will be interpreted as index and not as the id. I think casting it to Integer will fix the problem. Whats the idea of the running tasks arraylist? If its not important I would just call getScheduler().cancelTask(id) for now.
```
    public void stopTask(int taskId) {
        if (this.runningTasks.contains(taskId)) {
            Bukkit.getScheduler().cancelTask(taskId);
            this.runningTasks.remove(taskId);
        }
    }```

**Comment by ByteZ1337** [comment]
The only purpose of the `runningTasks` ArrayLists is to prevent `TaskManager#stopTask` from being used to stop BukkitTasks that weren't started by ParticleLib. But you're right, it's pretty useless. I'll remove the list in the next update.

**Comment by ByteZ1337** [comment]
The new version with a bugfix is [now released](https://github.com/ByteZ1337/ParticleLib/releases/tag/1.6.3). 
Thanks for reporting this issue.
