### ISSUE TITLE
Particles duplicate in every world

### ISSUE THREAD

**Issue by EmberCM** [ByteZ1337/ParticleLib#16]
Spigot Version: 1.8.8 Spigot
ParticleLib Version: 1.6.3

Description:
Using the method `ParticleEffect#display(Location, float, float, float, float, int, ParticleData)`, the particles seem to duplicate to multiple worlds as seen in the pictures below. Worlds "world" and "world_nether" are shown. Each of the methods are called with "world" as the world set in the location parameter.
![2021-07-09_15 29 43](https://user-images.githubusercontent.com/17890775/125128211-5a1c9800-e0c3-11eb-9327-860c0975eca5.png)
![2021-07-09_15 30 01](https://user-images.githubusercontent.com/17890775/125128210-5a1c9800-e0c3-11eb-83ba-b7b4483d3904.png)

**Comment by ByteZ1337** [comment]
Minecraft doesn't serialize the world into the packet. ParticleLib currently sends the packets to every online player, which leads to this “duplication”. I can add a filter for the display methods, but it will impact performance a lot.

**Comment by EmberCM** [comment]
I see. So if I were to supply the list of players to the method, this wouldn't happen?
Also, I think it would be a good idea to mention somewhere that this happens.

**Comment by ByteZ1337** [comment]
Yes, if you supply a list of all players in that world, only those players will see it. A hotfix should be released shortly, so you don't have to fix it yourself (Unless you're using ParticleTasks).

**Comment by ByteZ1337** [comment]
Fixed in [1.6.4](https://github.com/ByteZ1337/ParticleLib/releases/tag/1.6.4)
