### ISSUE TITLE
Particles are displaying in all worlds

### ISSUE THREAD

**Issue by JoaoGabrielCostaa** [ByteZ1337/ParticleLib#18]
Hello, i trying to display a Helix with particles in one world and one location, but my code with your library is displaying the helix in all worlds in the same X , Y  and Z. (Video [https://www.youtube.com/watch?v=jr_dwEfkwiU](https://www.youtube.com/watch?v=jr_dwEfkwiU))

Can you help me?

```java
private int createNPCHelix(Entity npc) {
		if(npc == null) return 0;
		final int radius = 1;
		Location npcLocation = npc.getLocation();
		List<Object> packets = new ArrayList<>();
		ParticleBuilder particleBuilder = new ParticleBuilder(particle);
		for(int t = 0; t < 20; t++) {
			double x = radius * Math.cos(t);
			double z = radius * Math.sin(t);
			packets.add(particleBuilder.setLocation(npcLocation.clone().add(x, 0.5, z)).toPacket());
		}
		ParticleTask task = new GlobalTask(packets, 3);
		return TaskManager.getTaskManager().startTask(task);
	}
```

**Comment by ByteZ1337** [comment]
I'm aware of the issue (see #16). Sadly, Mojang doesn't serialize the world into the particle packets, which leads to them being displayed in every world. The only thing you can do right now is implement your own ParticleTask class. This should do the trick:
```java
public final class WorldTask extends ParticleTask {
    
    private final World world;
    
    public WorldTask(List<Object> packets, int tickDelay, World world) {
        super(packets, tickDelay);
        this.world = world;
    }
    
    @Override
    public Collection<Player> getTargetPlayers() {
        return world.getPlayers();
    }
}
```
I'll keep the issue open as a reminder to include it in the next version.

**Comment by ByteZ1337** [comment]
WorldTasks are now added in [1.6.5](https://github.com/ByteZ1337/ParticleLib/releases/tag/1.6.5). The [Wiki example](https://github.com/ByteZ1337/ParticleLib/wiki/ParticleTasks) has been updated as well to include this new implementation.
This version also includes a fix for another plugin field issue. So you now have to use ``ReflectionUtils#setPlugin`` instead of just setting the ``ReflectionUtils#plugin`` field.
