### ISSUE TITLE
ParticleBuilder.setOffset(Vector) changes all offset values to just the x value of the given vector

### ISSUE THREAD

**Issue by sepiatonal** [ByteZ1337/ParticleLib#21]
https://github.com/ByteZ1337/ParticleLib/blob/a3f7a595cdea3feb13340323f1a161a44f0df3e3/src/main/java/xyz/xenondevs/particle/ParticleBuilder.java#L192

I assume that this isn't intentional, but I don't know for sure.

**Comment by ByteZ1337** [comment]
It's not intentional, I'll fix it later
