### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by corentingosselin** [ByteZ1337/ParticleLib#29]
Can you add the long distance option via your particle builder ?
https://wiki.vg/Protocol#Particle_2

So we can increase the range :)

**Comment by ByteZ1337** [comment]
long distance is always set to ``true`` currently. So you can't increase it.
https://github.com/ByteZ1337/ParticleLib/blob/5b9c81c05613c099966cd7ba0e7969cfdc29c43e/src/main/java/xyz/xenondevs/particle/ParticlePacket.java#L386-L390
And I don't really see any use case for setting it to false.

**Comment by corentingosselin** [comment]
> long distance is always set to `true` currently. So you can't increase it.
> 
> https://github.com/ByteZ1337/ParticleLib/blob/5b9c81c05613c099966cd7ba0e7969cfdc29c43e/src/main/java/xyz/xenondevs/particle/ParticlePacket.java#L386-L390
> 
> 
> And I don't really see any use case for setting it to false.

Nice ! I did not notice that thank's
