### ISSUE TITLE
Issue for Spigot version 1.8.8!

### ISSUE THREAD

**Issue by Raconteur37** [ByteZ1337/ParticleLib#32]
Hello! I'm a developer over at mc.renatusnetwork.com and are working on a sequel for one of our top games! Due to the restrictions of combat on minecraft versions past 1.8, we have to run our gamemode off this version because of this, it makes us run spigot on 1.8 as well. As you may know spigot 1.8 simply has little to no particle control and in order to make this game as big as we want, we definitely need to get more particles in the library and running. With that, we found this plugin but got errors when trying to actually use the particles. I would appreciate any help with solving this issue and allowing us to get more particles. Thank you!

![image_2022-05-13_214703263](https://user-images.githubusercontent.com/69336066/168408044-fc89765d-a7e3-4d05-b949-bc0bc8f1dcec.png)

P.S, it should be noted that we are installing the project through maven.

**Comment by ByteZ1337** [comment]
Are you shading ParticleLib into your plugin?

**Comment by Raconteur37** [comment]
No, this is the only directory I have in our maven compiler. The jar file is in my lib folder and I just directly path it, how would I go about shading it? 
![image_2022-05-14_112022111](https://user-images.githubusercontent.com/69336066/168440229-51d532df-81f8-4dbc-b18c-91e5f5edd958.png)

**Comment by ByteZ1337** [comment]
Why are you adding it via a local path if it's on maven central? There should be plenty of tutorials about maven shade on YouTube.
