### ISSUE TITLE
1.19 particles not displayed

### ISSUE THREAD

**Issue by corentingosselin** [ByteZ1337/ParticleLib#33]
Hello, 

I am currently updating my plugin for 1.19 and seems like particles are not rendered
I'm running the latest spigot version and latest version of your dependency 
![image](https://user-images.githubusercontent.com/8132994/175811450-31226528-9da7-45e9-bc89-558ec65bd999.png)

My code:

```
            new ParticleBuilder(ParticleEffect.EXPLOSION_HUGE, player.getLocation())
                    .setOffsetY(1f)
                    .setSpeed(0.1f)
                    .setAmount(10)
                    .display();
            player.sendMessage("particle");
```

More info:

![image](https://user-images.githubusercontent.com/8132994/175811579-96cfefa7-e8c7-49ef-b87b-c251287abef4.png)
The particle section in f3 mode is always to 0

**Comment by ByteZ1337** [comment]
Works fine ![](https://i.imgur.com/EZK7dgo.png)

**Comment by corentingosselin** [comment]
Yep sorry for useless bothering,
The issue is caused by this maven part:

```
        <dependency>
            <groupId>xyz.xenondevs</groupId>
            <artifactId>particle</artifactId>
            <version>1.8.1</version>
            <scope>provided</scope> <---- must be removed
        </dependency>
```

I don't know why I did not get class not found exception

**Comment by corentingosselin** [comment]
Oh well nope
Forgot about this new feature in plugin.yml
I forgot to update that:

```
libraries:
  - xyz.xenondevs:particle:1.7.1
```
