### ISSUE TITLE
Error when using particles in Paper 1.19.3

### ISSUE THREAD

**Issue by I2000C** [ByteZ1337/ParticleLib#39]
Hi, yesterday I updated my plugin (https://github.com/I2000C/NewAmazingLuckyBlocks) to support Paper 1.19.3 (https://api.papermc.io/v2/projects/paper/versions/1.19.3/builds/384/downloads/paper-1.19.3-384.jar).
However, when I try to use the **VILLAGER_HAPPY** particle, the next error happens:

![error enderman soup](https://user-images.githubusercontent.com/29607352/214844284-f2f31ca9-edc4-4e08-b7a7-5a4f1b8d452d.png)

And this is the **line 35** of my class EndermanSoup:
![image](https://user-images.githubusercontent.com/29607352/214844187-70bbfd2a-9679-4694-ae23-e6e84ca78a75.png)

This error **didn't happen in Paper 1.19.2**.
Do you know what could be causing this error?

NOTE: I'm using the latest version (1.8.3) of ParticleLib (with is shaded in my plugin using Gradle).

**Comment by ByteZ1337** [comment]
![image](https://user-images.githubusercontent.com/42820438/214876764-c16160c2-9bdf-4505-b886-487cbf7465c5.png)

Works fine. Try cleaning your Gradle cache and check if the shaded ParticleLib version is actually `1.8.3`

**Comment by I2000C** [comment]
Sorry, I hadn't updated the build.gradle. Thanks for your help
