### ISSUE TITLE
Option to forcefully show particles despite of client settings

### ISSUE THREAD

**Issue by FaMa91** [ByteZ1337/ParticleLib#42]
In Spigot there is a 'force' parameter in the World.spawnParticle method to show particles despite of the user settings. Is it possible to add this option?

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#spawnParticle(org.bukkit.Particle,double,double,double,int,double,double,double,double,T,boolean)

Thank you

**Comment by ByteZ1337** [comment]
longDistance is hardcoded to true in ParticleLib

**Comment by FaMa91** [comment]
Ok for long distance, but what about showing the particle to a player regardless of the settings?
