### ISSUE TITLE
NullPointerException (Client) when using BlockTexture

### ISSUE THREAD

**Issue by kaonashi97** [ByteZ1337/ParticleLib#8]
Hello,

nice plugin! I'm using it for my own server on 1.16.3 and have now faced complications with Spigots internal legacy support. Plugins not using the api-version settings in plugin.yml (introduced in 1.13) may lead to load the old legacy support.
More information about this is provided by Spigot on https://www.spigotmc.org/wiki/plugin-yml/#optional-attributes under api-version section.
You mind adding the api-version to your plugin.yml in the next update?
```
api-version: 1.14
```

I used this code in a event listener method:
```
new ParticleBuilder(particle, location).setParticleData(new BlockTexture(Material.GLASS)).display();
```

It seems that `getBlockData()` in `BlockTexture` is causing this, because the call on `material.name()` goes to class `CraftLegacy` in the OBC. If edited the plugin.yml and it worked out of box. The call above is working and resolving to OBC Material.name() instead.

Thanks for this nice plugin and your work
~Kaonashi

**Comment by ByteZ1337** [comment]
Hey!

I didn't know not adding "api-version" will lead to an issues sorry about that. Is there a specific reason to change it to 1.14, not 1.16?

**Comment by kaonashi97** [comment]
Hi, thanks for your fast response.

When I tested it seems that not using this will active Spigots compatibility mode for plugins of older versions. This enforces the Material enum to delegate it's calls to OBC CraftLegacy class.
Thus only calls with the "old" legacy materials (e.g. `Material.LEGACY_GLASS`) are working. I've never seen that myself before so I don't know exactly how it behaves.
I saw this message in log written by Spigot on startup.

```
[2020-10-10 22:13:42] [WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[2020-10-10 22:13:45] [WARN]: Legacy plugin ParticleLib v1.5.1 does not specify an api-version.
```

That seems to be my fault as I copied it from another plugin to test if it would break things, when using Spigot 1.16 on 1.14... but as far as I tested it worked. The earliest version is 1.13 and the latest is 1.16. I think you should take the version the most you tested. It seems that `api-version` tells which Materials, Blocks, etc. your plugin is supporting and older ones aren't allowed anymore. I think taking the lower most is fine as you provide an API and not a specific content aware plugin.

This should not count for Spigot versions below 1.13 as they don't know about this flag.

**Comment by ByteZ1337** [comment]
I added `api-version: 1.14` to the latest ParticleLib-Plugin.jar release.
Let me know if it fixes your issue.

**Comment by kaonashi97** [comment]
I've tested with the same code as above on 1.16.3 Spigot and it worked perfectly.
Thanks for this fast fix!
